### ISSUE TITLE
what do different states mean?

### ISSUE THREAD

**Issue by josh-m-sharpe** [leomylonas/cordova-plugin-applicationstate#2]
Hi @leomylonas - do you think you could update the README to define what the three states returned by this plugin mean?  In particular - "inactive"

Thanks!

**Comment by leomylonas** [comment]
@josh-m-sharpe I've updated the readme (15253b9e260f96c823fe8a9d5884293db466b8d5)

**Comment by josh-m-sharpe** [comment]
Thank you sir!
