### ISSUE TITLE
cordova 7.x can't install plugin

### ISSUE THREAD

**Issue by josh-m-sharpe** [leomylonas/cordova-plugin-applicationstate#3]
I think it's because there's no package.json

cordova plugin add co.mylonas.cordova.applicationstate

Error: Failed to fetch plugin https://github.com/leomylonas/cordova-plugin-applicationstate.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm ERR! addLocal Could not install /var/folders/8d/psl4_tyd38b7c_y2qwyxwdz80000gn/T/npm-82607-4984a1ed/git-cache-51ca0f3d/15253b9e260f96c823fe8a9d5884293db466b8d5
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "https://github.com/leomylonas/cordova-plugin-applicationstate.git" "--save"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:

**Comment by leomylonas** [comment]
Hey Josh. Have you tried installing using the git URL like this...
`cordova plugin add https://github.com/leomylonas/cordova-plugin-applicationstate.git`

**Comment by josh-m-sharpe** [comment]
Hey Leo -- yea I have and I get the same result.  Late last night, I thought I found something that suggested package.json is required now.... but I can't find it right now.  I forked and tried it anyways, with no luck - https://github.com/josh-m-sharpe/cordova-plugin-applicationstate/commit/ee1463bec22cd20e9c5525b70b5a0cd8e1418289

Still looking around...

**Comment by josh-m-sharpe** [comment]
Aha!  package.json needed a 'version' attr.  So, this works from my fork:

cordova plugin add https://github.com/josh-m-sharpe/cordova-plugin-applicationstate.git

**Comment by josh-m-sharpe** [comment]
more info here:
http://cordova.apache.org/news/2017/05/04/cordova-7.html
See `--nofetch`

**Comment by leomylonas** [comment]
Looks like some other people have already forked and made similar changes, so I've just merged in one of them. Suggest you bring your fork up to date :)

**Comment by josh-m-sharpe** [comment]
thanks! :)
